name: "ZeroTier"
description: "Connect your Github Action workflow to ZeroTier"
branding:
  icon: "globe"
  color: "gray-dark"

on:
  workflow_call:

inputs:
  network_id:
    description: "The ZeroTier network ID to connect to"
    required: true
  auth_token:
    description: "Your ZeroTier Central API Access Token"
    required: true
  api_url:
    description: "ZeroTier Central API URL"
    required: false
    default: "https://my.zerotier.com/api/v1"

runs:
  using: "composite"
  steps:
    - name: zerotier
      uses: zonneplan/zerotier-github-action/util/post@main
      env:
        API_URL: ${{ inputs.api_url }}
        AUTH_TOKEN: ${{ inputs.auth_token }}
        NETWORK_ID: ${{ inputs.network_id }}
      with:
        main: $GITHUB_ACTION_PATH/main.sh
        post: $GITHUB_ACTION_PATH/post.sh
